name: Julia1.11

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          
      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Set CI environment variables
        run: |
          echo "JULIA_NUM_THREADS=1" >> $GITHUB_ENV
          echo "MERA_CI_MODE=true" >> $GITHUB_ENV
          echo "MERA_TEST_TIMEOUT=1800" >> $GITHUB_ENV
          echo "MERA_DOWNLOAD_RETRIES=3" >> $GITHUB_ENV
          
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run comprehensive test suite
        uses: julia-actions/julia-runtest@v1
        with:
          coverage: true
          test_args: '--threads=1'
        env:
          JULIA_NUM_THREADS: 1
          MERA_CI_MODE: true
          MERA_TEST_TIMEOUT: 1800
          MERA_DOWNLOAD_RETRIES: 3

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
        if: matrix.version == '1.11' && matrix.os == 'ubuntu-latest'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.version == '1.11' && matrix.os == 'ubuntu-latest'
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true

      - name: Upload coverage to Coveralls
        uses: julia-actions/julia-uploadcoveralls@v1
        if: matrix.version == '1.11' && matrix.os == 'ubuntu-latest'
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
