name: Julia1.11

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          
      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Set CI environment variables (reduced test mode)
        run: |
          echo "JULIA_NUM_THREADS=1" >> $GITHUB_ENV
          echo "MERA_CI_MODE=true" >> $GITHUB_ENV
          echo "MERA_SKIP_HEAVY=true" >> $GITHUB_ENV
          echo "MERA_SKIP_AQUA=true" >> $GITHUB_ENV
          echo "MERA_ZULIP_DRY_RUN=true" >> $GITHUB_ENV
          echo "MERA_BASIC_ZULIP_TESTS=true" >> $GITHUB_ENV
          echo "MERA_TEST_TIMEOUT=1200" >> $GITHUB_ENV
          echo "MERA_DOWNLOAD_RETRIES=2" >> $GITHUB_ENV
          
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run reduced test suite (compatibility check)
        uses: julia-actions/julia-runtest@v1
        with:
          test_args: '--threads=1'
        env:
          JULIA_NUM_THREADS: 1
          MERA_CI_MODE: true
          MERA_SKIP_HEAVY: true
          MERA_SKIP_AQUA: true
          MERA_ZULIP_DRY_RUN: true
          MERA_BASIC_ZULIP_TESTS: true
          MERA_TEST_TIMEOUT: 1200
          MERA_DOWNLOAD_RETRIES: 2

      # No coverage upload - this is compatibility testing only
