name: Coverage (Local Full Test)

# This workflow is designed to run locally or manually on GitHub
# It runs the complete test suite with full coverage and uploads to Codecov/Coveralls
# Use: gh workflow run coverage_local.yml --ref master

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      julia_version:
        description: 'Julia version to test'
        required: false
        default: '1.11'
        type: choice
        options:
          - '1.10'
          - '1.11'
      threads:
        description: 'Number of Julia threads'
        required: false
        default: '4'
        type: choice
        options:
          - '1'
          - '2'
          - '4'
          - '8'
      skip_heavy:
        description: 'Skip heavy simulation tests'
        required: false
        default: false
        type: boolean

jobs:
  full-coverage:
    name: Full Coverage Test - Julia ${{ github.event.inputs.julia_version || '1.11' }} (${{ github.event.inputs.threads || 4 }} threads)
    runs-on: macos-latest  # Use macOS for your local environment compatibility
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ github.event.inputs.julia_version || '1.11' }}
          arch: x64
          
      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Set full test environment
        run: |
          echo "JULIA_NUM_THREADS=${{ github.event.inputs.threads || 4 }}" >> $GITHUB_ENV
          echo "MERA_CI_MODE=false" >> $GITHUB_ENV
          echo "MERA_LOCAL_COVERAGE=true" >> $GITHUB_ENV
          echo "MERA_TEST_TIMEOUT=3600" >> $GITHUB_ENV
          echo "MERA_DOWNLOAD_RETRIES=3" >> $GITHUB_ENV
          # Optional heavy test skip
          if [ "${{ github.event.inputs.skip_heavy }}" = "true" ]; then
            echo "MERA_SKIP_HEAVY=true" >> $GITHUB_ENV
          fi
          # Notification tests: allow real network if configured, otherwise dry-run
          echo "MERA_ZULIP_ENABLE_NETWORK=true" >> $GITHUB_ENV
          
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run full test suite with coverage
        uses: julia-actions/julia-runtest@v1
        with:
          coverage: true
          test_args: '--threads=${{ github.event.inputs.threads || 4 }}'
        env:
          JULIA_NUM_THREADS: ${{ github.event.inputs.threads || 4 }}
          MERA_CI_MODE: false
          MERA_LOCAL_COVERAGE: true
          MERA_TEST_TIMEOUT: 3600
          MERA_DOWNLOAD_RETRIES: 3
          MERA_ZULIP_ENABLE_NETWORK: true

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
          flags: full-test,multi-thread

      - name: Upload coverage to Coveralls
        uses: julia-actions/julia-uploadcoveralls@v1
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-julia-${{ github.event.inputs.julia_version || '1.11' }}-threads-${{ github.event.inputs.threads || 4 }}
          path: |
            lcov.info
            *.cov
            test/*.cov
            *.png
          retention-days: 7
